PREFIX p: <http://dbpedia.org/property/>
PREFIX o: <http://dbpedia.org/ontology/>
PREFIX xs: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT DISTINCT ?ans WHERE
{
    ?s rdf:type o:River .
    ?s p:length ?l .                           
    FILTER (xs:integer(?l)) .
    OPTIONAL
    {
        ?s rdfs:label ?ans .
        FILTER (lang(?ans ) = 'en')
    }
}
ORDER BY DESC(?l)
LIMIT 1