BASE <http://rdfa.info/test-suite/test-cases/rdfa1.1/html4/0226.html>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://www.example.org/> 
ASK WHERE {
  <> rdf:value ("Foo");
    ex:inlist <res> .
  <res> rdf:value ("Bar") .
}
