ASK WHERE {
    <http://rdfa.info/test-suite/test-cases/rdfa1.1-role/html5-invalid/0314.html#b> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#banner>.
    <http://rdfa.info/test-suite/test-cases/rdfa1.1-role/html5-invalid/0314.html#toc> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#contentinfo>.
    <http://rdfa.info/test-suite/test-cases/rdfa1.1-role/html5-invalid/0314.html#contents> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#list>.
    <http://rdfa.info/test-suite/test-cases/rdfa1.1-role/html5-invalid/0314.html#a1> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#appendix>.
    <http://rdfa.info/test-suite/test-cases/rdfa1.1-role/html5-invalid/0314.html#s1> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#section>.
    <http://rdfa.info/test-suite/test-cases/rdfa1.1-role/html5-invalid/0314.html#s2> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#section>.
    <http://rdfa.info/test-suite/test-cases/rdfa1.1-role/html5-invalid/0314.html#main> <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#main>.
    [] <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#listitem>.
    [] <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#heading>.
    [] <http://www.w3.org/1999/xhtml/vocab#role> <http://www.w3.org/1999/xhtml/vocab#note>.
}
