PREFIX rdfa: <http://www.w3.org/ns/rdfa#>
PREFIX schema: <http://schema.org/>
ASK WHERE {
  ?r a schema:Person; schema:name "Amanda" ; schema:band ?b .
  ?b a schema:MusicGroup; schema:name "Jazz Band"; schema:size "12" .
  OPTIONAL {
    ?p a rdfa:Pattern; .
  }
  FILTER (! bound (?p))
}