/*
// <copyright>
// dotNetRDF is free and open source software licensed under the MIT License
// -------------------------------------------------------------------------
// 
// Copyright (c) 2009-2017 dotNetRDF Project (http://dotnetrdf.org/)
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is furnished
// to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDS.RDF.Query.Spin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SparqlTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SparqlTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VDS.RDF.Query.Spin.SparqlTemplates", typeof(SparqlTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFIX rdf:&lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt;
        ///PREFIX sd:&lt;http://www.w3.org/ns/sparql-service-description#&gt;
        ///PREFIX dnr:&lt;dotnetrdf-spin:&gt;
        ///
        ///DELETE {
        ///	GRAPH ?g {
        ///		?s ?p ?o .
        ///	} .
        ///	GRAPH ?entailment {
        ///		?s ?subP ?o .
        ///		?s a ?subC .
        ///	} .
        ///	GRAPH @outputGraph {
        ///		?s a ?subC .
        ///	} .
        ///}
        ///INSERT {
        ///	GRAPH ?g {
        ///		?s ?resetRequired ?p .
        ///		?s ?p ?otherValues .
        ///	} .
        ///	GRAPH @outputGraph {
        ///		?s ?resetRequired ?p .
        ///		@outputGraph dnr:hasChanged  ?s .
        ///	} .
        ///}
        ///@USING_NAMED
        ///USING NAMED @dataset [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFIX rdf:&lt;http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt;
        ///PREFIX sd:&lt;http://www.w3.org/ns/sparql-service-description#&gt;
        ///PREFIX dnr:&lt;dotnetrdf-spin:&gt;
        ///
        ///INSERT {
        ///	GRAPH ?g {
        ///		?s ?p ?o .
        ///	} .
        ///	GRAPH ?entailment {
        ///		?s ?supP ?o .
        ///		?s a ?supC .
        ///	} .
        ///	GRAPH @outputGraph {
        ///		?s a ?newSupC .
        ///		@outputGraph dnr:hasChanged  ?s .
        ///	} .
        ///}
        ///@USING_DEFAULT
        ///@USING_NAMED
        ///USING NAMED @datasetUri
        ///USING NAMED @outputGraph
        ///WHERE {
        ///	GRAPH @datasetUri {
        ///	    ?addedTriples dnr:addTriplesTo ?g .
        ///		OPTIONAL {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertData {
            get {
                return ResourceManager.GetString("InsertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFIX dnr:&lt;dotnetrdf-spin:&gt;
        ///DELETE {
        ///	GRAPH @resourceRestriction {
        ///		@resourceRestriction dnr:executionRestrictedTo ?s .
        ///	}
        ///}
        ///INSERT {
        ///	GRAPH @resourceRestriction {
        ///		?s a ?class .
        ///	}
        ///}
        ///USING @resourceRestrictions
        ///@USING_DEFAULT
        ///WHERE {
        ///	GRAPH @resourceRestriction {
        ///		@resourceRestriction dnr:executionRestrictedTo ?s .
        ///	} .
        ///	?s a ?class .
        ///}.
        /// </summary>
        internal static string SetExecutionContext {
            get {
                return ResourceManager.GetString("SetExecutionContext", resourceCulture);
            }
        }
    }
}
