// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using System;
using System.Collections.Generic;
using System.Text;
using VDS.RDF.Linq;
using NUnit.Framework;

namespace UnitTests
{
	[TestFixture]
	public class XsdtTypeConverterTest
	{
		[Test]
		public void ConstructorTest()
		{
			XsdtTypeConverter target = new XsdtTypeConverter();

			Assert.IsNotNull(target);
			Assert.IsNotNull(target.TypeLookup);
		}

		[Test]
		public void GetDataTypeTest()
		{
			XsdtTypeConverter target = new XsdtTypeConverter();

			Type t = typeof (string); 

			XsdtPrimitiveDataType expected = XsdtPrimitiveDataType.XsdtString;
			XsdtPrimitiveDataType actual;

			actual = target.GetDataType(t);

			Assert.AreEqual(expected, actual, "VDS.RDF.Linq.XsdtTypeConverter.GetDataType did not return the expected value.");
		}

		[Test]
		public void GetXsdtDateRepresentationForTest()
		{
			XsdtTypeConverter target = new XsdtTypeConverter();

		    DateTime d = new DateTime(2007, 10, 17, 19, 42, 01); 
            
			XsdtPrimitiveDataType dt = XsdtPrimitiveDataType.XsdtDateTime; 

			XsdtAttribute attr = new XsdtAttribute(true, "dateTime");

			string expected = "2007-10-17T19:42:01+" + ((d.IsDaylightSavingTime())?"01:00":"00:00");
			string actual;
            XsdtTypeConverter tc = new XsdtTypeConverter();
			actual = tc.GetXsdtDateRepresentationFor(d, dt, attr);

			Assert.AreEqual(expected, actual,
			                "VDS.RDF.Linq.XsdtTypeConverter.GetXsdtDateRepresentationFor did not return the expec" +
			                "ted value.");
		}

		[Test]
		public void TestXsdtTypeConversions()
		{
			XsdtTypeConverter target = new XsdtTypeConverter();
			Assert.IsTrue(target.Get("hello world").ToString() == "\"hello world\"");
			Assert.IsTrue(target.Get('a').ToString() == "\"a\"");
			Assert.IsTrue(target.Get(true).ToString() == "True^^xsd:boolean");
			Assert.IsTrue(target.Get(false).ToString() == "False^^xsd:boolean");
			Assert.IsTrue(target.Get((float) 3.14).ToString() == "3.14^^xsd:float");
			Assert.IsTrue(target.Get(3.14).ToString() == "3.14^^xsd:double");
			Assert.IsTrue(target.Get(3.14M).ToString() == "3.14^^xsd:decimal");
			Assert.IsTrue(target.Get(new TimeSpan(0, 5, 0)).ToString() == "\"00:05:00\"^^xsd:duration");
			Assert.IsTrue(target.Get<Int16>(4).ToString() == "4^^xsd:short");
			Assert.IsTrue(target.Get(4).ToString() == "4");
			Assert.IsTrue(target.Get<Int64>(4).ToString() == "4^^xsd:long");
			Assert.IsTrue(target.Get<Byte[]>(ASCIIEncoding.ASCII.GetBytes("hello")).ToString() == "\"hello\"^^xsd:hexBinary");
		}

		[Test]
		public void TypeLookupTest()
		{
			XsdtTypeConverter target = new XsdtTypeConverter();

			Dictionary<XsdtPrimitiveDataType, Type> val = new Dictionary<XsdtPrimitiveDataType, Type>();
				// TODO: Assign to an appropriate value for the property

			target.TypeLookup = val;


			Assert.AreEqual(val, target.TypeLookup, "VDS.RDF.Linq.XsdtTypeConverter.TypeLookup was not set correctly.");
		}
	}
}