ASK WHERE {
<http://rdfa.info/test-suite/test-cases/rdfa1.1/xml/0115.xml>
   <http://www.example.com/entity1>
      ">" .
<http://rdfa.info/test-suite/test-cases/rdfa1.1/xml/0115.xml>
   <http://www.example.com/entity2>
      "Ben & Co." .
<http://rdfa.info/test-suite/test-cases/rdfa1.1/xml/0115.xml>
   <http://www.example.com/entity3>
      "@" .
<http://rdfa.info/test-suite/test-cases/rdfa1.1/xml/0115.xml>
   <http://www.example.com/entity4>
      "@" .
}
