PREFIX xhv: <http://www.w3.org/1999/xhtml/vocab#>
PREFIX cc: <http://creativecommons.org/ns#>
PREFIX rdfatest: <http://rdfa.info/vocabs/rdfa-test#>
ASK WHERE {
  <http://rdfa.info/test-suite/test-cases/rdfa1.1/xhtml5-invalid/0114.xhtml>
    xhv:index <http://rdfa.info/test-suite/#>;
    xhv:next <http://rdfa.info/test-suite/test-cases/rdfa1.1/xhtml5-invalid/0115.xhtml>;
    xhv:up <http://rdfa.info/test-suite/test-cases/rdfa1.1/xhtml5-invalid/>;
    cc:attributionURL <http://rdfa.info/>;
    rdfatest:cornerCase1 <http://rdfa.info/test-suite/test-cases/rdfa1.1/xhtml5-invalid/>;
    rdfatest:cornerCase3 <http://rdfa.info/test-suite/test-cases/rdfa1.1/xhtml5-invalid/...>;
    rdfatest:cornerCase4 <http://rdfa.info/test-suite/test-cases/rdfa1.1/xhtml5-invalid/0114.xhtml?foo=bar../baz>;
    rdfatest:cornerCase5 <http://rdfa.info/test-suite/test-cases/.../.htaccess>.
}
