ASK WHERE {
	?a <http://xmlns.com/foaf/0.1/mbox> <mailto:manu.sporny@digitalbazaar.com> .
	?b <http://xmlns.com/foaf/0.1/mbox> <mailto:gregg@kellogg-assoc.com> .
	?a <http://xmlns.com/foaf/0.1/knows> ?b .
	?b <http://xmlns.com/foaf/0.1/knows> ?a .
	FILTER ( isBlank(?a) && isBlank(?b) )
}