PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX afn: <http://jena.hpl.hp.com/ARQ/function#>
PREFIX lfn: <http://www.dotnetrdf.org/leviathan#>
PREFIX pf: <http://jena.hpl.hp.com/ARQ/property#>

SELECT *
WHERE 
{
  { ?s a ?type }
  UNION
  { GRAPH ?g { ?s a ?type } }
}