ASK WHERE {
 <http://rdfa.info/test-suite/test-cases/rdfa1.0/xml/0106.xml> <http://purl.org/dc/elements/1.1/creator>  ?a .
 OPTIONAL {
   ?x ?y <http://rdfa.info/test-suite/test-cases/rdfa1.0/xml/manu.html> .
 }
 FILTER (isBlank(?a) && !BOUND(?x) && !BOUND(?y))
}