ASK WHERE {
	<http://rdfa.info/test-suite/test-cases/rdfa1.1/html5/0054.html> <http://purl.org/dc/elements/1.1/creator> "Fabien Gandon" .
	<http://rdfa.info/test-suite/test-cases/rdfa1.1/html5/0054.html> <http://purl.org/dc/elements/1.1/publisher> "Fabien Gandon" .
}