PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

ASK WHERE {
  <http://rdfa.info/test-suite/test-cases/rdfa1.1/html5/0281.html> rdf:value "2012"^^xsd:gYear .
}