PREFIX po: <http://example.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK WHERE {
  ?s po:role [ rdfs:label <http://example.org/profiles/director.html>] .

  <http://example.org/profiles/director.html> a po:Role .
}
