//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDS.RDF.Utilities.StoreManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VDS.RDF.Utilities.StoreManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update active connections.
        /// </summary>
        internal static string ActiveConnections_Update_Error {
            get {
                return ResourceManager.GetString("ActiveConnections_Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for {0}.
        /// </summary>
        internal static string BrowseFor {
            get {
                return ResourceManager.GetString("BrowseFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clear connections.
        /// </summary>
        internal static string ClearConnections_Error {
            get {
                return ResourceManager.GetString("ClearConnections_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to {0} Failed.
        /// </summary>
        internal static string Connection_Failed {
            get {
                return ResourceManager.GetString("Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Close_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Close_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to close the connection {0}?  This will close all windows and tasks currently using this connection..
        /// </summary>
        internal static string ConnectionManagement_ConfirmClose_Text {
            get {
                return ResourceManager.GetString("ConnectionManagement_ConfirmClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Close.
        /// </summary>
        internal static string ConnectionManagement_ConfirmClose_Title {
            get {
                return ResourceManager.GetString("ConnectionManagement_ConfirmClose_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove the connection {0}?.
        /// </summary>
        internal static string ConnectionManagement_ConfirmRemove_Text {
            get {
                return ResourceManager.GetString("ConnectionManagement_ConfirmRemove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Remove.
        /// </summary>
        internal static string ConnectionManagement_ConfirmRemove_Title {
            get {
                return ResourceManager.GetString("ConnectionManagement_ConfirmRemove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to edit the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Edit_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Edit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Open_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Open_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Remove_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Remove_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to rename the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Rename_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Rename_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection must be in open state.
        /// </summary>
        internal static string ConnectionMustBeOpen {
            get {
                return ResourceManager.GetString("ConnectionMustBeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the Graph &apos;{0}&apos;?  This action is non-reversible.
        /// </summary>
        internal static string DeleteGraph_Confirm_Text {
            get {
                return ResourceManager.GetString("DeleteGraph_Confirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Graph Confirmation.
        /// </summary>
        internal static string DeleteGraph_Confirm_Title {
            get {
                return ResourceManager.GetString("DeleteGraph_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete the Store &apos;{0}&apos;?  This action is non-reversible.
        /// </summary>
        internal static string DeleteStore_Confirm_Text {
            get {
                return ResourceManager.GetString("DeleteStore_Confirm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Store Confirmation.
        /// </summary>
        internal static string DeleteStore_Confirm_Title {
            get {
                return ResourceManager.GetString("DeleteStore_Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Connection.
        /// </summary>
        internal static string EditConnection {
            get {
                return ResourceManager.GetString("EditConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit an open connection, please close the connection before attempting to edit it.
        /// </summary>
        internal static string EditConnection_Forbidden_Text {
            get {
                return ResourceManager.GetString("EditConnection_Forbidden_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Forbidden.
        /// </summary>
        internal static string EditConnection_Forbidden_Title {
            get {
                return ResourceManager.GetString("EditConnection_Forbidden_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a File to export to!.
        /// </summary>
        internal static string ExportData_NoFile_Text {
            get {
                return ResourceManager.GetString("ExportData_NoFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Export Destination.
        /// </summary>
        internal static string ExportData_NoFile_Title {
            get {
                return ResourceManager.GetString("ExportData_NoFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to clear your Favourite Connections?.
        /// </summary>
        internal static string FavouriteConnections_ConfirmClear_Text {
            get {
                return ResourceManager.GetString("FavouriteConnections_ConfirmClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Favourite Connections?.
        /// </summary>
        internal static string FavouriteConnections_ConfirmClear_Title {
            get {
                return ResourceManager.GetString("FavouriteConnections_ConfirmClear_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update favourite connections since there is no favourite connections file available.
        /// </summary>
        internal static string FavouriteConnections_NoFile {
            get {
                return ResourceManager.GetString("FavouriteConnections_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update favourite connections.
        /// </summary>
        internal static string FavouriteConnections_Update_Error {
            get {
                return ResourceManager.GetString("FavouriteConnections_Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph is not available.
        /// </summary>
        internal static string Graph_Unavailable_Text {
            get {
                return ResourceManager.GetString("Graph_Unavailable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Unavailable.
        /// </summary>
        internal static string Graph_Unavailable_Title {
            get {
                return ResourceManager.GetString("Graph_Unavailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected internal error occurred and Store Manager will close once you close this dialogue:
        ///{0}.
        /// </summary>
        internal static string HandleInternalError_Exit {
            get {
                return ResourceManager.GetString("HandleInternalError_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected internal error occurred:
        ///{0}.
        /// </summary>
        internal static string HandleInternalError_NonExit {
            get {
                return ResourceManager.GetString("HandleInternalError_NonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Example.
        /// </summary>
        internal static string HideExample {
            get {
                return ResourceManager.GetString("HideExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import data from an invalid URI - {0}.
        /// </summary>
        internal static string ImportData_InvalidSource_Text {
            get {
                return ResourceManager.GetString("ImportData_InvalidSource_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Import URI.
        /// </summary>
        internal static string ImportData_InvalidSource_Title {
            get {
                return ResourceManager.GetString("ImportData_InvalidSource_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import data to an Invalid Default Target Graph URI - {0}.
        /// </summary>
        internal static string ImportData_InvalidTarget_Text {
            get {
                return ResourceManager.GetString("ImportData_InvalidTarget_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Default Target Graph URI.
        /// </summary>
        internal static string ImportData_InvalidTarget_Title {
            get {
                return ResourceManager.GetString("ImportData_InvalidTarget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a File to import from!.
        /// </summary>
        internal static string ImportData_NoFile_Text {
            get {
                return ResourceManager.GetString("ImportData_NoFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File to Import.
        /// </summary>
        internal static string ImportData_NoFile_Title {
            get {
                return ResourceManager.GetString("ImportData_NoFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a URI to import from!.
        /// </summary>
        internal static string ImportData_NoUri_Text {
            get {
                return ResourceManager.GetString("ImportData_NoUri_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No URI to Import.
        /// </summary>
        internal static string ImportData_NoUri_Title {
            get {
                return ResourceManager.GetString("ImportData_NoUri_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        internal static string Internal_Error {
            get {
                return ResourceManager.GetString("Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid URI: {0}.
        /// </summary>
        internal static string InvalidUri_Text {
            get {
                return ResourceManager.GetString("InvalidUri_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI.
        /// </summary>
        internal static string InvalidUri_Title {
            get {
                return ResourceManager.GetString("InvalidUri_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to list Graphs due to the following error:
        ///{0}.
        /// </summary>
        internal static string ListGraphs_Error_Text {
            get {
                return ResourceManager.GetString("ListGraphs_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph List Unavailable.
        /// </summary>
        internal static string ListGraphs_Error_Title {
            get {
                return ResourceManager.GetString("ListGraphs_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Graph URI(s) were returned.
        /// </summary>
        internal static string ListGraphs_Information {
            get {
                return ResourceManager.GetString("ListGraphs_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to list Stores due to the following error:
        ///{0}.
        /// </summary>
        internal static string ListStores_Error_Text {
            get {
                return ResourceManager.GetString("ListStores_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store List Unavailable.
        /// </summary>
        internal static string ListStores_Error_Title {
            get {
                return ResourceManager.GetString("ListStores_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Store IDs were returned.
        /// </summary>
        internal static string ListStores_Information {
            get {
                return ResourceManager.GetString("ListStores_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to load the favourite, recent and active connections.
        /// </summary>
        internal static string LoadConnections_Error {
            get {
                return ResourceManager.GetString("LoadConnections_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New From Existing.
        /// </summary>
        internal static string NewFromExisting {
            get {
                return ResourceManager.GetString("NewFromExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current connection is not editable.
        /// </summary>
        internal static string NewFromExisting_Error_Text {
            get {
                return ResourceManager.GetString("NewFromExisting_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection from Current Error.
        /// </summary>
        internal static string NewFromExisting_Error_Title {
            get {
                return ResourceManager.GetString("NewFromExisting_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the given file due to the following error:
        ///{0}.
        /// </summary>
        internal static string OpenConnection_Error_Text {
            get {
                return ResourceManager.GetString("OpenConnection_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Connection Failed.
        /// </summary>
        internal static string OpenConnection_Error_Title {
            get {
                return ResourceManager.GetString("OpenConnection_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open a connection from the given file as it was not a valid RDF Graph or was in a format that the library does not understand.
        /// </summary>
        internal static string OpenConnection_InvalidFile_Text {
            get {
                return ResourceManager.GetString("OpenConnection_InvalidFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Store selected.
        /// </summary>
        internal static string OpenStore_Error_Text {
            get {
                return ResourceManager.GetString("OpenStore_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Store Error.
        /// </summary>
        internal static string OpenStore_Error_Title {
            get {
                return ResourceManager.GetString("OpenStore_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPARQL Query Error.
        /// </summary>
        internal static string Query_Error_Title {
            get {
                return ResourceManager.GetString("Query_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute a SPARQL Query since your Store does not support SPARQL.
        /// </summary>
        internal static string Query_Unsupported {
            get {
                return ResourceManager.GetString("Query_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to show Query Results as did not get a Graph/Result Set as expected.
        /// </summary>
        internal static string QueryResults_NotViewable_Text {
            get {
                return ResourceManager.GetString("QueryResults_NotViewable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Show Results.
        /// </summary>
        internal static string QueryResults_NotViewable_Title {
            get {
                return ResourceManager.GetString("QueryResults_NotViewable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Results are not available.
        /// </summary>
        internal static string QueryResults_Unavailable_Text {
            get {
                return ResourceManager.GetString("QueryResults_Unavailable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Unavailable.
        /// </summary>
        internal static string QueryResults_Unavailable_Title {
            get {
                return ResourceManager.GetString("QueryResults_Unavailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the connection due to the following error: {0}.
        /// </summary>
        internal static string QuickConnect_Error_Text {
            get {
                return ResourceManager.GetString("QuickConnect_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Connect Error.
        /// </summary>
        internal static string QuickConnect_Error_Title {
            get {
                return ResourceManager.GetString("QuickConnect_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to edit the Connection due to an error: {0}.
        /// </summary>
        internal static string QuickEdit_Error_Text {
            get {
                return ResourceManager.GetString("QuickEdit_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Edit Error.
        /// </summary>
        internal static string QuickEdit_Error_Title {
            get {
                return ResourceManager.GetString("QuickEdit_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update recent connections.
        /// </summary>
        internal static string RecentConnections_Update_Error {
            get {
                return ResourceManager.GetString("RecentConnections_Update_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to restore connection {0}.
        /// </summary>
        internal static string RestoreConnection_Error {
            get {
                return ResourceManager.GetString("RestoreConnection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected connection file already exists - would you like to append this connection to that file?  Click Yes to append to this file, No to overwrite and Cancel to abort.
        /// </summary>
        internal static string SaveConnection_Append_Text {
            get {
                return ResourceManager.GetString("SaveConnection_Append_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Connection?.
        /// </summary>
        internal static string SaveConnection_Append_Title {
            get {
                return ResourceManager.GetString("SaveConnection_Append_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save connection.
        /// </summary>
        internal static string SaveConnection_Error {
            get {
                return ResourceManager.GetString("SaveConnection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Example.
        /// </summary>
        internal static string ShowExample {
            get {
                return ResourceManager.GetString("ShowExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Opening Connection {0}:
        ///{1}.
        /// </summary>
        internal static string StartPage_Open_Error_Text {
            get {
                return ResourceManager.GetString("StartPage_Open_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Listing unavailable - Store is ready.
        /// </summary>
        internal static string Status_GraphListingUnavailable {
            get {
                return ResourceManager.GetString("Status_GraphListingUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store is ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Graph List....
        /// </summary>
        internal static string Status_RenderingGraphList {
            get {
                return ResourceManager.GetString("Status_RenderingGraphList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Store List....
        /// </summary>
        internal static string Status_RenderingStoreList {
            get {
                return ResourceManager.GetString("Status_RenderingStoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Listing unavailable - Store is ready.
        /// </summary>
        internal static string Status_StoreListUnavailable {
            get {
                return ResourceManager.GetString("Status_StoreListUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for Store to be ready before attempting to Import Data.
        /// </summary>
        internal static string StoreNoteReady_Import_Text {
            get {
                return ResourceManager.GetString("StoreNoteReady_Import_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for Store to be ready before attempting to make a SPARQL Query.
        /// </summary>
        internal static string StoreNotReady_Query_Text {
            get {
                return ResourceManager.GetString("StoreNotReady_Query_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Not Ready.
        /// </summary>
        internal static string StoreNotReady_Title {
            get {
                return ResourceManager.GetString("StoreNotReady_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for Store to be ready before attempting to make a SPARQL Update.
        /// </summary>
        internal static string StoreNotReady_Update_Text {
            get {
                return ResourceManager.GetString("StoreNotReady_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on {1}.
        /// </summary>
        internal static string TaskForm_Title {
            get {
                return ResourceManager.GetString("TaskForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Information cannot be shown as the Task type is unknown.
        /// </summary>
        internal static string TaskInfo_Unavailable_Text {
            get {
                return ResourceManager.GetString("TaskInfo_Unavailable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Information Unavailable.
        /// </summary>
        internal static string TaskInfo_Unavailable_Title {
            get {
                return ResourceManager.GetString("TaskInfo_Unavailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triples Counted.
        /// </summary>
        internal static string TriplesCounted {
            get {
                return ResourceManager.GetString("TriplesCounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mode: Approximated.
        /// </summary>
        internal static string UpdarteModeApproximated {
            get {
                return ResourceManager.GetString("UpdarteModeApproximated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Mode: Native.
        /// </summary>
        internal static string UpdateModeNative {
            get {
                return ResourceManager.GetString("UpdateModeNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Graph Failed due to the following error: {0}.
        /// </summary>
        internal static string ViewGraph_Error_Text {
            get {
                return ResourceManager.GetString("ViewGraph_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Graph Failed.
        /// </summary>
        internal static string ViewGraph_Error_Title {
            get {
                return ResourceManager.GetString("ViewGraph_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Graph Failed due to an unknown error.
        /// </summary>
        internal static string ViewGraph_UnknownError_Text {
            get {
                return ResourceManager.GetString("ViewGraph_UnknownError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
