//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VDS.RDF.Utilities.StoreManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VDS.RDF.Utilities.StoreManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to close the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Close_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Close_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to close the connection {0}?  This will close all windows and tasks currently using this connection..
        /// </summary>
        internal static string ConnectionManagement_ConfirmClose_Text {
            get {
                return ResourceManager.GetString("ConnectionManagement_ConfirmClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Close.
        /// </summary>
        internal static string ConnectionManagement_ConfirmClose_Title {
            get {
                return ResourceManager.GetString("ConnectionManagement_ConfirmClose_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove the connection {0}?.
        /// </summary>
        internal static string ConnectionManagement_ConfirmRemove_Text {
            get {
                return ResourceManager.GetString("ConnectionManagement_ConfirmRemove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Remove.
        /// </summary>
        internal static string ConnectionManagement_ConfirmRemove_Title {
            get {
                return ResourceManager.GetString("ConnectionManagement_ConfirmRemove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to edit the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Edit_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Edit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Open_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Open_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove the connection {0}.
        /// </summary>
        internal static string ConnectionManagement_Remove_Error {
            get {
                return ResourceManager.GetString("ConnectionManagement_Remove_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected internal error occurred and Store Manager will close once you close this dialogue:
        ///.
        /// </summary>
        internal static string HandleInternalError_Exit {
            get {
                return ResourceManager.GetString("HandleInternalError_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected internal error occurred:
        ///.
        /// </summary>
        internal static string HandleInternalError_NonExit {
            get {
                return ResourceManager.GetString("HandleInternalError_NonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        internal static string Internal_Error {
            get {
                return ResourceManager.GetString("Internal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
