CREATE TABLE GRAPHS (graphID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
					 graphURI TEXT CHARACTER SET utf8,
					 graphHash INT NOT NULL);
					 
CREATE TABLE GRAPH_TRIPLES (graphID INT NOT NULL,
							tripleID INT NOT NULL,
							CONSTRAINT GraphTriplesPKey PRIMARY KEY (graphID, tripleID));

CREATE TABLE NODES (nodeID INT NOT NULL PRIMARY KEY,
					nodeType TINYINT NOT NULL,
					nodeValue TEXT CHARACTER SET utf8 COLLATE utf8_bin,
					nodeHash INT NOT NULL);

CREATE TABLE TRIPLES (tripleID INT NOT NULL PRIMARY KEY,
					  tripleSubject INT NOT NULL,
					  triplePredicate INT NOT NULL,
					  tripleObject INT NOT NULL,
					  tripleHash INT NOT NULL);
					  
CREATE TABLE NS_URIS (nsUriID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
					  nsUri TEXT CHARACTER SET utf8,
					  nsUriHash INT NOT NULL);

CREATE TABLE NS_PREFIXES (nsPrefixID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
						  nsPrefix NVARCHAR(50));
						  
CREATE TABLE NAMESPACES (nsID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
						 graphID INT NOT NULL,
						 nsPrefixID INT NOT NULL,
						 nsUriID INT NOT NULL);